# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  OpenGLPlayground_config = debug

else ifeq ($(config),release)
  OpenGLPlayground_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := OpenGLPlayground

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

OpenGLPlayground:
ifneq (,$(OpenGLPlayground_config))
	@echo "==== Building OpenGLPlayground ($(OpenGLPlayground_config)) ===="
	@${MAKE} --no-print-directory -C . -f OpenGLPlayground.make config=$(OpenGLPlayground_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f OpenGLPlayground.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   OpenGLPlayground"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"